apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vibevoice
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress-apex.yaml
  - ingress-www.yaml
images:
  - name: registry.144.91.77.245.sslip.io/vibevoice
    newName: registry.144.91.77.245.sslip.io/vibevoice
    newTag: latest
