apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vibevoice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gateszhangc/vibevoice.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: vibevoice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

