apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: vibevoice
images:
  - name: registry.144.91.77.245.sslip.io/vibevoice
    newName: registry.144.91.77.245.sslip.io/vibevoice
    newTag: latest
